---
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:
  - name: copy docker-compose.yml
    copy:
      src: ./docker-compose.yml
      dest: ./docker-compose.yml
  - name: run docker-compose
    docker_service:
      project_src: .
      state: present
      restarted: yes
