---
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:
  - name: log into private repo
    docker_login:
      registry: 142.93.68.244
      username: admin
      password: hoog0ree
      reauthorize: yes
  - name: copy docker-compose.yml
    copy:
      src: ./docker-compose.yml
      dest: ./docker-compose.yml
  - name: run docker-compose
    docker_service:
      project_src: .
      build: yes
      nocache: yes
      pull: yes
      state: present
      recreate: always
      restarted: yes
